### ISSUE TITLE
Funtionalitet til at sende og modtage data - Pi

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/Pi#2]
Implementer funktionaliteten så Pi'en faktisk kan sende data til App'en, og at denne modtager det.

Laves sammen med:
- [ ] P8-Team/App#4

Afhængig af:
- [ ] P8-Team/App#1 
- [x] #1

**Comment by soenderby** [comment]
This is no longer necessary, as the functionality will be implemented on the same device, and perhaps even same program
